version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./public:/app/public
      - ./server:/app/server
      - ./tests:/app/tests
    command: >
      npm start
