name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm start &
      - run: npx wait-on http://localhost:3001
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: vercel/action@v2
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
